import { CreateWalletSimulationKeys, SimulationType } from "../types";

/**
 *
 * @returns {SimulationType[]} - Array of Create wallet simulation data
 */
export const getCreateWalletSimulationData = (): SimulationType[] => {
  const data: SimulationType[] = [
    {
      name: "Introduction",
      slug: "introduction",
      renderBlocks: [
        {
          subHeader: "Introduction",
          list: [
            {
              head: "What are emulations - why is this the future of web3 education?",
              body: [
                {
                  paragraph:
                    "Emulation is the process of imitating a hardware/software program/platform on another program or platform. This makes it possible to run programs on systems not designed for them. Emulators, as the name implies, emulate the functions of one system on another. Thus, the second system behaves like the original system, attempting to exactly reproduce the external behaviors of the first system.",
                },
              ],
            },
            {
              head: "What will you be learning to emulate?",
              body: [
                {
                  paragraph:
                    "Emulation is the process of imitating a hardware/software program/platform on another program or platform. This makes it possible to run programs on systems not designed for them. Emulators, as the name implies, emulate the functions of one system on another. Thus, the second system behaves like the original system, attempting to exactly reproduce the external behaviors of the first system.",
                },
              ],
            },
            {
              head: "Why should you care about creating a wallet? ",
              body: [
                {
                  paragraph:
                    "Emulation is the process of imitating a hardware/software program/platform on another program or platform. This makes it possible to run programs on systems not designed for them. Emulators, as the name implies, emulate the functions of one system on another. Thus, the second system behaves like the original system, attempting to exactly reproduce the external behaviors of the first system.",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      name: "Create a wallet",
      slug: "create-a-wallet",
      renderBlocks: [
        {
          subHeader: "Create your first wallet ever!",
          list: [
            {
              head: "What are seed phrases?",
              body: [
                {
                  paragraph:
                    "A recovery phrase (sometimes known as a seed phrase) is a series of words generated by your cryptocurrency wallet that gives you access to the crypto associated with that wallet. Think of a wallet as being similar to a password manager for crypto, and the recovery phrase as being like the master password. As long as you have your recovery phrase, you’ll have access to all of the crypto associated with the wallet that generated the phrase — even if you delete or lose the wallet.",
                },
              ],
            },
            {
              head: "Why is it important to keep recovery phase safe?",
              body: [
                {
                  paragraph:
                    "There’s a wide range of strategies about how to best secure recovery phrases, which tend to vary based on how much crypto you have and how much you value security vs. convenience.",
                  pointHeader: "Some of the best practices include",
                  points: [
                    "Write down your recovery phrase on paper and store it in a safe place.",
                    "Store your recovery phrase in a password manager.",
                    "Store your recovery phrase in a hardware wallet.",
                    "One very powerful way to secure a recovery phrase would be to split it between safe deposit boxes in multiple locations (making sure there’s redundancy in case something were to happen to any of the locations). Obviously this is not very convenient.",
                    "Some people use specialized services to engrave recovery phrases into durable materials like stainless steel.",
                  ],
                },
              ],
            },
            {
              head: "Let’s generate a keypair!",
              body: [
                {
                  paragraph: "Below is the Simulation for Creating a wallet",
                },
              ],

              simKey: CreateWalletSimulationKeys.GenKeyPair,
            },
          ],
        },
      ],
    },
    {
      name: "Backup Seed Phrase",
      slug: "backup-seed-phrase",
      renderBlocks: [
        {
          subHeader: "Backup your Seed Phrase 🤫",
          list: [
            {
              head: "What is this? Why do I have to back it up? What happens if I lose it?",
              body: [
                {
                  paragraph:
                    "A recovery phrase (sometimes known as a seed phrase) is a series of words generated by your cryptocurrency wallet that gives you access to the crypto associated with that wallet. Think of a wallet as being similar to a password manager for crypto, and the recovery phrase as being like the master password. As long as you have your recovery phrase, you’ll have access to all of the crypto associated with the wallet that generated the phrase — even if you delete or lose the wallet.",
                },
              ],
            },
            {
              head: "Let's back it up!",
              body: [
                {
                  paragraph:
                    "Below is the Simulation for backing up your seed phrase.",
                },
              ],

              simKey: CreateWalletSimulationKeys.BackupSeedPhrase,
            },
          ],
        },
      ],
    },
    {
      name: "Showcase the Public Key",
      slug: "showcase-the-public-key",
      renderBlocks: [
        {
          subHeader: "Go “Public” in Web3",
          list: [
            {
              head: "What is Public Key?",
              body: [
                {
                  paragraph:
                    "Simply put, a public key is a unique identifier for a wallet. It is a string of characters that is used to send and receive crypto. It is also used to verify that a transaction was sent by the owner of the wallet.",
                  image:
                    "https://media.giphy.com/media/1xrbiAultrDDq/giphy.gif",
                },
              ],
            },
            {
              head: "Behold, your Public Key! 🎉",
              body: [
                {
                  paragraph:
                    "Simply put, a public key is a unique identifier for a wallet. It is a string of characters that is used to send and receive crypto. It is also used to verify that a transaction was sent by the owner of the wallet.",
                },
              ],
              simKey: CreateWalletSimulationKeys.ShowcasePublicKey,
            },
          ],
        },
      ],
    },
    {
      name: "Request for testnet airdrop on for the wallet",
      slug: "request-for-testnet-airdrop-on-for-the-wallet",
      renderBlocks: [
        {
          subHeader: "Request for testnet airdrop on for the wallet",
          list: [
            {
              head: "I made a wallet, now what? 🤔",
              body: [
                {
                  paragraph:
                    "Web3 Wallets have set a new industry standard in creating new ways to own and monetize our content, identity, and assets as we move on towards the next generation of the internet. Simply put, Web3 wallets are a way to use hardware or software not only to access funds, but to effortlessly allow you to interact with decentralized applications, serve as a gateway to bankless financial services, collect NFTs, create on-chain identity, collaborate with communities, and provide substantially more use cases beyond the scope of the traditional wallets we have today. Just like how people have a physical wallet to store paper money, these wallets help store access to your digital currency instead. In addition, Web3 wallets are capable of storing digital assets such as NFTs and enable users to interact with Decentralized Apps (dApps). This is done all without the necessity of a middleman involved. Wallets don’t actually store the cryptocurrency, but they store the information required for access to your funds which are digital cryptocurrencies.",
                },
              ],
            },
            {
              head: "What is an Airdrop?",
              body: [
                {
                  paragraph:
                    "Web3 Wallets have set a new industry standard in creating new ways to own and monetize our content, identity, and assets as we move on towards the next generation of the internet. Simply put, Web3 wallets are a way to use hardware or software not only to access funds, but to effortlessly allow you to interact with decentralized applications, serve as a gateway to bankless financial services, collect NFTs, create on-chain identity, collaborate with communities, and provide substantially more use cases beyond the scope of the traditional wallets we have today. Just like how people have a physical wallet to store paper money, these wallets help store access to your digital currency instead. In addition, Web3 wallets are capable of storing digital assets such as NFTs and enable users to interact with Decentralized Apps (dApps). This is done all without the necessity of a middleman involved. Wallets don’t actually store the cryptocurrency, but they store the information required for access to your funds which are digital cryptocurrencies.",
                  image:
                    "https://media.giphy.com/media/12QCczVAjPAfvi/giphy.gif",
                },
              ],
            },
            {
              head: "What Different the networks (testnet?? 😵‍💫)",
              body: [
                {
                  paragraph:
                    "Web3 Wallets have set a new industry standard in creating new ways to own and monetize our content, identity, and assets as we move on towards the next generation of the internet. Simply put, Web3 wallets are a way to use hardware or software not only to access funds, but to effortlessly allow you to interact with decentralized applications, serve as a gateway to bankless financial services, collect NFTs, create on-chain identity, collaborate with communities, and provide substantially more use cases beyond the scope of the traditional wallets we have today. Just like how people have a physical wallet to store paper money, these wallets help store access to your digital currency instead. In addition, Web3 wallets are capable of storing digital assets such as NFTs and enable users to interact with Decentralized Apps (dApps). This is done all without the necessity of a middleman involved. Wallets don’t actually store the cryptocurrency, but they store the information required for access to your funds which are digital cryptocurrencies.",
                },
              ],
            },
            {
              head: "Check your balance! 💸",
              body: [
                {
                  paragraph:
                    "Web3 Wallets have set a new industry standard in creating new ways to own and monetize our content, identity, and assets as we move on towards the next generation of the internet. Simply put, Web3 wallets are a way to use hardware or software not only to access funds, but to effortlessly allow you to interact with decentralized applications, serve as a gateway to bankless financial services, collect NFTs, create on-chain identity, collaborate with communities, and provide substantially more use cases beyond the scope of the traditional wallets we have today. Just like how people have a physical wallet to store paper money, these wallets help store access to your digital currency instead. In addition, Web3 wallets are capable of storing digital assets such as NFTs and enable users to interact with Decentralized Apps (dApps). This is done all without the necessity of a middleman involved. Wallets don’t actually store the cryptocurrency, but they store the information required for access to your funds which are digital cryptocurrencies.",
                },
              ],

              simKey: CreateWalletSimulationKeys.Airdrop,
            },
          ],
        },
      ],
    },
  ];

  return data;
};
